In [3]:
import pandas as pd
import numpy as np
import seaborn as sns

df = sns.load_dataset("tips")

print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (244, 7)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [5]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [7]:
print("Rows before removing duplicates:", df.shape)

df = df.drop_duplicates()

print("Rows after removing duplicates:", df.shape)

Rows before removing duplicates: (244, 7)
Rows after removing duplicates: (243, 7)

In [8]:
df.columns = df.columns.str.strip()
df.columns = df.columns.str.lower()

print(df.columns)

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [9]:
high_tip = df[df['tip'] > 5]
print(high_tip.head())

    total_bill   tip     sex smoker  day    time  size
23       39.42  7.58    Male     No  Sat  Dinner     4
44       30.40  5.60    Male     No  Sun  Dinner     4
47       32.40  6.00    Male     No  Sun  Dinner     4
52       34.81  5.20  Female     No  Sun  Dinner     4
59       48.27  6.73    Male     No  Sat  Dinner     4

In [10]:
high_bill = df[df['total_bill'] > 30]
print(high_bill.head())

    total_bill   tip     sex smoker  day    time  size
11       35.26  5.00  Female     No  Sun  Dinner     4
23       39.42  7.58    Male     No  Sat  Dinner     4
39       31.27  5.00    Male     No  Sat  Dinner     3
44       30.40  5.60    Male     No  Sun  Dinner     4
47       32.40  6.00    Male     No  Sun  Dinner     4

In [11]:
female_customers = df[df['sex'] == 'Female']
print(female_customers.head())

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
11       35.26  5.00  Female     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2
16       10.33  1.67  Female     No  Sun  Dinner     3

In [12]:
sorted_bill = df.sort_values(by='total_bill', ascending=False)
print(sorted_bill.head())

     total_bill    tip   sex smoker  day    time  size
170       50.81  10.00  Male    Yes  Sat  Dinner     3
212       48.33   9.00  Male     No  Sat  Dinner     4
59        48.27   6.73  Male     No  Sat  Dinner     4
156       48.17   5.00  Male     No  Sun  Dinner     6
182       45.35   3.50  Male    Yes  Sun  Dinner     3

In [13]:
sorted_tip = df.sort_values(by='tip', ascending=False)
print(sorted_tip.head())

     total_bill    tip   sex smoker   day    time  size
170       50.81  10.00  Male    Yes   Sat  Dinner     3
212       48.33   9.00  Male     No   Sat  Dinner     4
23        39.42   7.58  Male     No   Sat  Dinner     4
59        48.27   6.73  Male     No   Sat  Dinner     4
141       34.30   6.70  Male     No  Thur   Lunch     6

In [14]:
avg_bill = np.mean(df['total_bill'])
print("Average Total Bill:", avg_bill)

Average Total Bill: 19.813868312757204

In [15]:
min_bill = np.min(df['total_bill'])
print("Minimum Bill:", min_bill)

Minimum Bill: 3.07

In [16]:
total_tip = np.sum(df['tip'])
print("Total Tips Collected:", total_tip)

Total Tips Collected: 729.5799999999999

In [17]:
avg_tip_gender = df.groupby('sex')['tip'].mean()
print(avg_tip_gender)

sex
Male      3.089618
Female    2.843140
Name: tip, dtype: float64

/tmp/ipykernel_611/121909016.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  avg_tip_gender = df.groupby('sex')['tip'].mean()

In [18]:
bill_by_day = df.groupby('day')['total_bill'].sum()
print(bill_by_day)

day
Thur    1083.33
Fri      325.88
Sat     1778.40
Sun     1627.16
Name: total_bill, dtype: float64

/tmp/ipykernel_611/3120877281.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  bill_by_day = df.groupby('day')['total_bill'].sum()

In [20]:
tip_by_day = df.groupby('day')['tip'].mean()
print(tip_by_day)

day
Thur    2.784098
Fri     2.734737
Sat     2.993103
Sun     3.255132
Name: tip, dtype: float64

/tmp/ipykernel_611/2929425930.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tip_by_day = df.groupby('day')['tip'].mean()

In [21]:
customers_by_time = df.groupby('time')['size'].sum()
print(customers_by_time)

time
Lunch     162
Dinner    463
Name: size, dtype: int64

/tmp/ipykernel_611/794233744.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  customers_by_time = df.groupby('time')['size'].sum()

In [22]:
df.to_csv("tips_cleaned_dataset.csv", index=False)

In [23]:
import os
os.listdir()

['.config', 'tips_cleaned_dataset.csv', 'sample_data']